files: ^computer-use-demo/
default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        name: Run `ruff` to autofix lint errors
        args: [--fix-only]
      - id: ruff
        name: Run `ruff` to format code
        entry: ruff format --force-exclude
      - id: ruff
        name: Run `ruff` to lint code
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.384
    hooks:
      - id: pyright
